### ISSUE TITLE
[Application] Unable to edit application

### ISSUE THREAD

**Issue by areeta** [hackuci/HackUCI-Site#24]
I'm not able to edit my application after I have confirmed my email. Should it be editable?

<img width="203" alt="Screen Shot 2020-12-07 at 6 14 33 PM" src="https://user-images.githubusercontent.com/20546538/101429554-1016ce00-38b8-11eb-899b-8cc2551f897d.png">

**Comment by zpinto** [comment]
Kevin fixed it
