### ISSUE TITLE
[Home] Horizontally Center Top Text

### ISSUE THREAD

**Issue by katzhou99** [hackuci/HackUCI-Site#44]
Migrated from Google Doc:

Would it be possible to center all the text at the top vertically? Don't worry if not! This is lower priority.
![image](https://user-images.githubusercontent.com/26679007/101438951-51af7500-38c8-11eb-8950-62ed817db67d.png)

**Comment by LasseNordahl** [comment]
This one I can try to tackle a little better, it's hard to find a spot that works at all resolutions. I'll update with some screenshots
