### ISSUE TITLE
[Application] Error for "Reupload in File Format" overlaps with other text, hard to read

### ISSUE THREAD

**Issue by sylvesteryue** [hackuci/HackUCI-Site#45]
![image](https://user-images.githubusercontent.com/56140648/101438973-5f64fa80-38c8-11eb-8f62-ced5c357b35a.png)

Red text that shows that the file uploaded is not in PDF format and need to be reuploaded is obscured by other text.

**Comment by RileyChampion** [comment]
Also the same result happens when you submit a resume that works
![image](https://user-images.githubusercontent.com/47626030/101439135-b8349300-38c8-11eb-9280-df9b34fa9c62.png)

**Comment by zpinto** [comment]
repeat
