### ISSUE TITLE
[Login] Fix card view length

### ISSUE THREAD

**Issue by areeta** [hackuci/HackUCI-Site#48]
On Mac Pro!

<img width="1440" alt="Screen Shot 2020-12-07 at 8 13 45 PM" src="https://user-images.githubusercontent.com/20546538/101439144-bd91dd80-38c8-11eb-84d8-3c3cbed24c67.png">

**Comment by katzhou99** [comment]
Just some extra details. I used 477 for the card width in the designs, but feel free to adjust as needed!
