### ISSUE TITLE
[Sponsor Us] Statistics Cards Spacing

### ISSUE THREAD

**Issue by katzhou99** [hackuci/HackUCI-Site#51]
Migrated from Google Doc:

- The statistics cards get very close to each other at times. Would it be possible to set a higher minimum padding?
![image](https://user-images.githubusercontent.com/26679007/101439251-0184e280-38c9-11eb-9b3a-92fe7de6c621.png)

- Could we increase the left padding for the text on these statistics cards? It’s a bit too close to the edge. I used 26pts in my design, but if that looks off, feel free to mess around.
![image](https://user-images.githubusercontent.com/26679007/101439282-0d70a480-38c9-11eb-89fc-25d9319e33c9.png)

**Comment by crystalleesf** [comment]
![IMG_2160](https://user-images.githubusercontent.com/31254896/101439707-f4b4be80-38c9-11eb-87e5-33a5b77fcab4.PNG)
The "First time Hackers" Card doesn't match in size on the mobile version

**Comment by Nauxie** [comment]
> The "First time Hackers" Card doesn't match in size on the mobile version
> <img alt="" height="300" src="https://user-images.githubusercontent.com/31254896/101439707-f4b4be80-38c9-11eb-87e5-33a5b77fcab4.PNG">

I kinda purposely made it like this to match the design in figma:
![image](https://user-images.githubusercontent.com/37749663/101554419-7577c700-396b-11eb-8465-de02380314ae.png)

But I can make it all match, what do you think @katzhou99 ?

**Comment by Nauxie** [comment]
added padding to `.last-year__stat`

**Comment by katzhou99** [comment]
hmm I don't have any strong opinions on this. But if Crystal would prefer it and if it's not too much trouble for you @Nauxie, I'm down to switch over.

**Comment by crystalleesf** [comment]
oh it's not a big deal to me haha, but i think on the desktop version they're equal

**Comment by Nauxie** [comment]
Alright sounds good ill leave it how it is rn!
