### ISSUE TITLE
[Login] General Error when Logging In after applying

### ISSUE THREAD

**Issue by LasseNordahl** [hackuci/HackUCI-Site#55]
![Screen Shot 2020-12-07 at 8 20 51 PM](https://user-images.githubusercontent.com/13127625/101439652-ccc55b00-38c9-11eb-8cd8-ac741b388d2f.png)

**Comment by LasseNordahl** [comment]
Logged out, can't log back in. 99% sure on password.

**Comment by zpinto** [comment]
@nathan-tang Instead of saying "something went wrong" as the error message, can we use the message that comes back from the server. It says "something went wrong" even when just the password is incorrect.
