### ISSUE TITLE
[RSVP] Phone number field accepts any kind of string

### ISSUE THREAD

**Issue by sylvesteryue** [hackuci/HackUCI-Site#58]
When RSVPing to go to HackUCI, users can input any type of string into phone number field, such as a string full of alphabet characters, as opposed to inputting a correctly formatted phone number.

**Comment by nathan-tang** [comment]
Regex for US phone numbers: /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/im
//probably just check for only valid numbers to account for international numbers
