### ISSUE TITLE
[Home] Background Formatting(?) Vertical Monitor

### ISSUE THREAD

**Issue by kingsleyszeto** [hackuci/HackUCI-Site#59]
![image](https://user-images.githubusercontent.com/41782066/101439936-88868a80-38ca-11eb-9bf6-8cc5be51a08a.png)

**Comment by LasseNordahl** [comment]
dis issue makes me cry

**Comment by kingszeto** [comment]
im very sorry i have a vertical monitor

**Comment by LasseNordahl** [comment]
hehe it's ok i think ill be able to figure it out

**Comment by LasseNordahl** [comment]
this background was spooky to get working across all

**Comment by kingszeto** [comment]
b i g b r a i n
