### ISSUE TITLE
[Login/Forgot Password/Apply/Confirmation] Opacity is too Low

### ISSUE THREAD

**Issue by katzhou99** [hackuci/HackUCI-Site#62]
It might just be me, but it looks as if all the text and items on the cards in these pages have decreased opacity. This seems to apply to all pages with the text and transparent grey card format. For example, the white text isn't fully white and the text field background is lighter than it should be. Could we double-check that if we're decreasing the opacity of the items and fix if needed?

![image](https://user-images.githubusercontent.com/26679007/101440011-ae139400-38ca-11eb-8a1e-efe0d97ac051.png)
_Here, "Application" looks whiter than "Basic Information"._

**Comment by nathan-tang** [comment]
TIL i'm color blind, I had to zoom in so much to see this.
