### ISSUE TITLE
[Home] Scrolling down yields this blue area, which quickly disappears iPhone X

### ISSUE THREAD

**Issue by kingszeto** [hackuci/HackUCI-Site#64]
![](https://cdn.discordapp.com/attachments/606008972289245194/785725010668027904/image.png)

**Comment by kingszeto** [comment]
it's the bottom part, everytime you scroll up (to the very top) then go down, this thing appears and promptly disappears.

**Comment by LasseNordahl** [comment]
This is an IOS bug, not sure if I can fix? I'll update the gradient tho
