### ISSUE TITLE
[Dashboard] Does not update after clicking decision

### ISSUE THREAD

**Issue by jogplus** [hackuci/HackUCI-Site#67]
If I click the "Sorry I can't make it" button, it does not update the Dashboard page. I have to refresh manually.
![Screen Shot 2020-12-07 at 8 28 23 PM](https://user-images.githubusercontent.com/24497772/101440461-9ab4f880-38cb-11eb-9ad3-d389f1403f9e.png)

**Comment by zpinto** [comment]
@kevinfang2 change current status to Declined when cannot attend button is clicked
