### ISSUE TITLE
[Home] Ant Size

### ISSUE THREAD

**Issue by katzhou99** [hackuci/HackUCI-Site#77]
The ants get huge and take up most of the screen when I decrease the width of the browser. Could we set a maximum size for these guys? This is lower priority though, so don't worry till you have time :)

![image](https://user-images.githubusercontent.com/26679007/101442257-d356d100-38cf-11eb-88d7-b1f6d97e96e3.png)

**Comment by LasseNordahl** [comment]
https://github.com/hackuci/HackUCI-Site/pull/82

close when this is merged

**Comment by zpinto** [comment]
https://github.com/hackuci/HackUCI-Site/pull/82
