### ISSUE TITLE
[Home] Volunteer Descriptions Should be Left-Alligned

### ISSUE THREAD

**Issue by katzhou99** [hackuci/HackUCI-Site#81]
![image](https://user-images.githubusercontent.com/26679007/101442786-e0c08b00-38d0-11eb-82db-6ba728b9e411.png)

**Comment by LasseNordahl** [comment]
https://github.com/hackuci/HackUCI-Site/pull/82

should be fixed when this is merged

**Comment by zpinto** [comment]
#82
