### ISSUE TITLE
[Home] Mentor apply button and sponsor button link to nothing

### ISSUE THREAD

**Issue by zpinto** [hackuci/HackUCI-Site#88]
![Screen Shot 2020-12-07 at 9 49 55 PM](https://user-images.githubusercontent.com/20071182/101445425-4e22ea80-38d6-11eb-85b9-9aa8b137ca5d.png)

The mentor button can link to nothing for now but the sponsor button should link to the sponsor page.

**Comment by LasseNordahl** [comment]
closing with merge of branch content
