### ISSUE TITLE
[Body Text] Body text size differs between Home and Sponsors pages

### ISSUE THREAD

**Issue by katzhou99** [hackuci/HackUCI-Site#92]
The body text size on Home looks smaller than the body text size on Sponsors. Both should be 18.

Home
![image](https://user-images.githubusercontent.com/26679007/101450327-3ef46a80-38df-11eb-85a0-79d09e903819.png)

Sponsors
![image](https://user-images.githubusercontent.com/26679007/101450364-4ddb1d00-38df-11eb-92aa-7c2fecb01e66.png)

**Comment by Nauxie** [comment]
fixed by changing `font-size' of `.mainpage__subtext` from 18px to 1.3rem to match Home page text
